### ISSUE TITLE
MP3 Function not working

### ISSUE THREAD

**Issue by CodePunk-** [MrS0m30n3/youtube-dl-gui#151]
```1/31/17 09:59:05] [debug] System config: []
[01/31/17 09:59:05] [debug] User config: []
[01/31/17 09:59:05] [debug] Custom config: []
[01/31/17 09:59:05] [debug] Command-line args: ['--newline', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-k', '-o', 'E:\\YT\\yt\\%(playlist_index)s-%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--ignore-config', '--hls-prefer-native', '--embed-thumbnail', 'https://www.youtube.com/watch?v=34Na4j8AVgA']
[01/31/17 09:59:05] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[01/31/17 09:59:05] [debug] youtube-dl version 2017.01.29
[01/31/17 09:59:05] [debug] Python version 3.4.4 - Windows-10-10.0.14393
[01/31/17 09:59:05] [debug] exe versions: ffmpeg N-82794-g3ab1311, ffprobe N-82794-g3ab1311
[01/31/17 09:59:05] [debug] Proxy map: {}
[01/31/17 09:59:05] ERROR: Signature extraction failed: Traceback (most recent call last):
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
[01/31/17 09:59:05] ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
[01/31/17 09:59:05]  (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/17 09:59:05] Traceback (most recent call last):
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
[01/31/17 09:59:05] ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
[01/31/17 09:59:05] Traceback (most recent call last):
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
[01/31/17 09:59:05] ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
[01/31/17 09:59:05] 
[01/31/17 09:59:05] During handling of the above exception, another exception occurred:
[01/31/17 09:59:05] 
[01/31/17 09:59:05] Traceback (most recent call last):
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 369, in extract
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1646, in _real_extract
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1067, in _decrypt_signature
[01/31/17 09:59:05] youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
[01/31/17 09:59:05]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
[01/31/17 09:59:05]   File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
[01/31/17 09:59:05] ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
[01/31/17 09:59:05]  (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/17 09:59:05] 
```

**Comment by MrS0m30n3** [comment]
Hi, @CodePunk- 

Sorry for the late response. I managed to re-create the issue on Windows.
Basically the first time you run *youtube-dlg* it seems that it cannot locate **ffmpeg** & **ffprobe** for some reason. Also, from a quick view your log errors seem completely unrelated to the mp3 issue.

I'm pretty busy right now but i'm going to take a closer look on the issue in the next days.

**Comment by MrS0m30n3** [comment]
@CodePunk- 

Bug reproduce steps (build [b791ac8](https://drive.google.com/file/d/0B4LUjPpAKNa1SkVJYVhnak1JMTA/view)) :
1. Run youtube-dl-gui.exe
2. Change directory using the "**...**" button
3. Select **mp3** as output format
4. Try to download a new URL
5. You should get an **Error** status (*could not locate ffmpeg*)

This behaviour was occurring due to the *DD_CHANGE_DIR* property of the wx.DirDialog widget.
You can download the new build from here [8e60ff3](https://drive.google.com/file/d/0B4LUjPpAKNa1M2FKMmZOTnJxM1U/view). Please let me know if it works for you.

For more informations regarding this bug you can check:
* Commit https://github.com/MrS0m30n3/youtube-dl-gui/commit/8e60ff336701fe8607ca9d3f9c6444bb72e109aa
* wx.DirDialog docs https://wxpython.org/Phoenix/docs/html/wx.DirDialog.html
