### ISSUE TITLE
error when download this video url

### ISSUE THREAD

**Issue by dreamboxgate** [MrS0m30n3/youtube-dl-gui#236]
https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0

**Comment by nodiscc** [comment]
@dreamboxgate Please reopen a new issue following the [Issue template](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by dreamboxgate** [comment]
can you explain more ?

**Comment by nodiscc** [comment]
* follow the instructions at https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/.github/ISSUE_TEMPLATE.md#bug-report and copy/paste your youtube-dlg log here. We need detailed information to help you (exact error message), and that will be found in the log.
 * What youtube-dl-gui version are you using?
 * What operating system?
 * Can you run `Update` to update youtube-dl, and try again? Does this work?

All these questions are asked when you create a new issue. Don't delete the template text, read it, and add information where asked.

**Comment by dreamboxgate** [comment]
What youtube-dl-gui version are you using?
last version 

What operating system?
Windows 7

log file 

[11/03/17 13:25:12] [debug] System config: []
[11/03/17 13:25:12] [debug] User config: []
[11/03/17 13:25:12] [debug] Custom config: []
[11/03/17 13:25:12] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\ThE MaStEr\\Desktop\\Downloads\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0', 'https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0']
[11/03/17 13:25:12] [debug] Encodings: locale cp1256, fs mbcs, out cp1256, pref cp1256
[11/03/17 13:25:12] [debug] youtube-dl version 2017.10.29
[11/03/17 13:25:12] [debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[11/03/17 13:25:12] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[11/03/17 13:25:12] [debug] Proxy map: {}
[11/03/17 13:25:12] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/03/17 13:25:12] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/03/17 13:25:12] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12] Traceback (most recent call last):
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\vodplatform.py", line 30, in _real_extract
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 1072, in _sort_formats
[11/03/17 13:25:12] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12] 
[11/03/17 13:25:12] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/03/17 13:25:12] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/03/17 13:25:12] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12] Traceback (most recent call last):
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\vodplatform.py", line 30, in _real_extract
[11/03/17 13:25:12]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 1072, in _sort_formats
[11/03/17 13:25:12] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12]
