### ISSUE TITLE
I receive an error when selecting 1080p or higher

### ISSUE THREAD

**Issue by PrinceOfCrime** [MrS0m30n3/youtube-dl-gui#254]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[12/29/17 11:40:44] [debug] System config: []
[12/29/17 11:40:44] [debug] User config: []
[12/29/17 11:40:44] [debug] Custom config: []
[12/29/17 11:40:44] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\Documents\\Technique\\%(title)s.%(ext)s', '-f', '46', '-v', '--ignore-config', '--hls-prefer-native', 'https://youtu.be/UyRiw2b8yI4']
[12/29/17 11:40:44] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[12/29/17 11:40:44] [debug] youtube-dl version 2017.12.28
[12/29/17 11:40:44] [debug] Python version 3.4.4 - Windows-10-10.0.14393
[12/29/17 11:40:44] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[12/29/17 11:40:44] [debug] Proxy map: {}
[12/29/17 11:40:44] ERROR: requested format not available
[12/29/17 11:40:44] Traceback (most recent call last):
[12/29/17 11:40:44]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
[12/29/17 11:40:44]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
[12/29/17 11:40:44]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 1614, in process_video_result
[12/29/17 11:40:44] youtube_dl.utils.ExtractorError: requested format not available
[12/29/17 11:40:44] 

```

#### What operating system do you use ?
Windows
#### List of actions to perform to reproduce the problem:

  1. .. Add url
  2. .. Select MP4/WebM 1080p/4k
  3. .. Receive Error after pre-processing
  
#### What is the expected behaviour ?
To Download the videos in 1080p/4k
#### What happens instead ?
It returns an error 

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

---

I'm trying to download videos from Youtube in 1080p/4k; I receive an error. The videos are in 1080p/4k, so that's not the problem. Thank you.

**Comment by MrS0m30n3** [comment]
As the error message states, the requested format is not available. Try a different format.

**Comment by EpicLPer** [comment]
Wouldn't it be nice to implement a convert function instead of just closing it, aka. it'll try to download either the source or the equivalent 1080p source and then convert it via ffmpeg?
