### ISSUE TITLE
heroku deploy error 

### ISSUE THREAD

**Issue by nk932714** [MrS0m30n3/youtube-dl-gui#265]
please check the log below 

```
-----> Python app detected

 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.

 !     Learn more: https://devcenter.heroku.com/articles/procfile

-----> Installing python-3.6.4

-----> Installing pip

-----> Installing requirements with pip

       Obtaining file:///tmp/build_fae7a90e4e89eb3aead1da9da87ff33d/nk932714-youtube-dl-gui-57eb51c (from -r /tmp/build_fae7a90e4e89eb3aead1da9da87ff33d/nk932714-youtube-dl-gui-57eb51c/requirements.txt (line 1))

           Complete output from command python setup.py egg_info:

           Traceback (most recent call last):

             File "<string>", line 1, in <module>

             File "/tmp/build_fae7a90e4e89eb3aead1da9da87ff33d/nk932714-youtube-dl-gui-57eb51c/setup.py", line 73, in <module>

               from youtube_dl_gui import (

             File "/tmp/build_fae7a90e4e89eb3aead1da9da87ff33d/nk932714-youtube-dl-gui-57eb51c/youtube_dl_gui/__init__.py", line 26

               print error

                         ^

           SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int error)?

           

           ----------------------------------------

       Command "python setup.py egg_info" failed with error code 1 in /tmp/build_fae7a90e4e89eb3aead1da9da87ff33d/nk932714-youtube-dl-gui-57eb51c/

 !     Push rejected, failed to compile Python app.

 !     Push failed

```

**Comment by MrS0m30n3** [comment]
Hi 
```
...
Installing python-3.6.4
...
```

Youtube-dl-gui does not support Python 3.* currently. Check [requirements](https://github.com/MrS0m30n3/youtube-dl-gui#requirements).

**Comment by nk932714** [comment]
Thanks for your quick reply. @MrS0m30n3

**Comment by nk932714** [comment]
please check the logs on 2.7.14 version 
```

-----> Python app detected

 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.

 !     Learn more: https://devcenter.heroku.com/articles/procfile

-----> Installing python-2.7.14

-----> Installing pip

-----> Installing requirements with pip

       Obtaining file:///tmp/build_c26a667966981e3a315c7f3cc9ce2816/nk932714-youtube-dl-gui-a79afd4 (from -r /tmp/build_c26a667966981e3a315c7f3cc9ce2816/nk932714-youtube-dl-gui-a79afd4/requirements.txt (line 1))

           Complete output from command python setup.py egg_info:

           No module named wx

           

           ----------------------------------------

       Command "python setup.py egg_info" failed with error code 1 in /tmp/build_c26a667966981e3a315c7f3cc9ce2816/nk932714-youtube-dl-gui-a79afd4/

 !     Push rejected, failed to compile Python app.

 !     Push failed

```

**Comment by nk932714** [comment]
Hi i think requirements.txt file is required Please add when you got time. 
Thanks in advance :)
