### ISSUE TITLE
random ffmpeg error

### ISSUE THREAD

**Issue by TheKessler0** [MrS0m30n3/youtube-dl-gui#277]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[02/24/18 21:30:25] [debug] System config: []
[02/24/18 21:30:25] [debug] User config: []
[02/24/18 21:30:25] [debug] Custom config: []
[02/24/18 21:30:25] [debug] Command-line args: ['--newline', '--playlist-start', '600', '-i', '-o', 'C:\\Users\\Public\\Documents\\Download.Music\\%(uploader)s\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--hls-prefer-native', '--embed-thumbnail', '--add-metadata', 'https://www.youtube.com/watch?v=pa4PqsTRb94&ab_channel=TrapNation']
[02/24/18 21:30:25] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[02/24/18 21:30:25] [debug] youtube-dl version 2018.02.22
[02/24/18 21:30:25] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[02/24/18 21:30:25] [debug] exe versions: ffprobe 3.3.2
[02/24/18 21:30:25] [debug] Proxy map: {}
[02/24/18 21:30:25] WARNING: pa4PqsTRb94: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
[02/24/18 21:30:25] ERROR: audio conversion failed: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] Traceback (most recent call last):
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 234, in run_ffmpeg
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 208, in run_ffmpeg
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 179, in run_ffmpeg_multiple_files
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 64, in check_version
[02/24/18 21:30:25] youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] 
[02/24/18 21:30:25] During handling of the above exception, another exception occurred:
[02/24/18 21:30:25] 
[02/24/18 21:30:25] Traceback (most recent call last):
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 305, in run
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 236, in run_ffmpeg
[02/24/18 21:30:25] youtube_dl.postprocessor.common.AudioConversionError: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] 
[02/24/18 21:30:25] During handling of the above exception, another exception occurred:
[02/24/18 21:30:25] 
[02/24/18 21:30:25] Traceback (most recent call last):
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 308, in run
[02/24/18 21:30:25] youtube_dl.utils.PostProcessingError: audio conversion failed: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] 
[02/24/18 21:30:25] ERROR: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] Traceback (most recent call last):
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 465, in run
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 179, in run_ffmpeg_multiple_files
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 64, in check_version
[02/24/18 21:30:25] youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] 
[02/24/18 21:30:25] ERROR: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] Traceback (most recent call last):
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\embedthumbnail.py", line 50, in run
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 179, in run_ffmpeg_multiple_files
[02/24/18 21:30:25]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\postprocessor\ffmpeg.py", line 64, in check_version
[02/24/18 21:30:25] youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg or avconv not found. Please install one.
[02/24/18 21:30:25] 

```

I use windows 10

I installed youtube dlg yesterday, all was fine, downloaded a very long play list (allmost 1000 vidoes, converted them to mp3) overnight. all was working! then i shutdown my system ....   so, today this shit happens:

so, im trying to download and convert a video to mp3...
it downloads, everything is normal, but then it stops, and the error says that im missing ffmpeg....
this only happens if i use the gui, the normal in commandline youtube dl is functioning fine...
but what realy bugs me is, that ive reinstalled all possible components manualy , but the same happens...
and again, commandline youtube dl is just fine.

**Comment by MrS0m30n3** [comment]
Seems similar to #151.
