### ISSUE TITLE
youtube-dlg 0.4 error

### ISSUE THREAD

**Issue by apenfl456** [MrS0m30n3/youtube-dl-gui#282]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[03/14/18 10:45:07] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:13:29] [debug] System config: []
[03/15/18 12:13:29] [debug] User config: []
[03/15/18 12:13:29] [debug] Custom config: []
[03/15/18 12:13:29] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=2lWJUrExG0U']
[03/15/18 12:13:29] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:13:29] [debug] youtube-dl version 2018.03.10
[03/15/18 12:13:29] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:13:29] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:13:29] [debug] Proxy map: {}
[03/15/18 12:13:29] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:15:39] [debug] System config: []
[03/15/18 12:15:39] [debug] User config: []
[03/15/18 12:15:39] [debug] Custom config: []
[03/15/18 12:15:39] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=LjE3X59lE3c']
[03/15/18 12:15:39] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:15:39] [debug] youtube-dl version 2018.03.10
[03/15/18 12:15:39] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:15:39] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:15:39] [debug] Proxy map: {}
[03/15/18 12:15:39] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:18:04] [debug] System config: []
[03/15/18 12:18:04] [debug] User config: []
[03/15/18 12:18:04] [debug] Custom config: []
[03/15/18 12:18:04] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-f', '37', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=3_Q-yYfjeBM&t=49s']
[03/15/18 12:18:04] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:18:04] [debug] youtube-dl version 2018.03.10
[03/15/18 12:18:04] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:18:04] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:18:04] [debug] Proxy map: {}
[03/15/18 12:18:04] ERROR: requested format not available
[03/15/18 12:18:04] Traceback (most recent call last):
[03/15/18 12:18:04]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
[03/15/18 12:18:04]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 850, in process_ie_result
[03/15/18 12:18:04]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 1615, in process_video_result
[03/15/18 12:18:04] youtube_dl.utils.ExtractorError: requested format not available
[03/15/18 12:18:04] 
[03/15/18 12:21:56] [debug] System config: []
[03/15/18 12:21:56] [debug] User config: []
[03/15/18 12:21:56] [debug] Custom config: []
[03/15/18 12:21:56] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=3_Q-yYfjeBM&t=49s']
[03/15/18 12:21:56] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:21:56] [debug] youtube-dl version 2018.03.10
[03/15/18 12:21:56] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:21:56] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:21:56] [debug] Proxy map: {}
[03/15/18 12:21:56] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10] [debug] System config: []
[03/15/18 12:31:10] [debug] System config: []
[03/15/18 12:31:10] [debug] User config: []
[03/15/18 12:31:10] [debug] User config: []
[03/15/18 12:31:10] [debug] Custom config: []
[03/15/18 12:31:10] [debug] Custom config: []
[03/15/18 12:31:10] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=LnIC7dFeGO0&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3']
[03/15/18 12:31:10] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=H6IsIWlSVkA&index=4&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3']
[03/15/18 12:31:10] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:31:10] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:31:10] [debug] youtube-dl version 2018.03.10
[03/15/18 12:31:10] [debug] youtube-dl version 2018.03.10
[03/15/18 12:31:10] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:31:10] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:31:10] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:31:10] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:31:10] [debug] Proxy map: {}
[03/15/18 12:31:10] [debug] Proxy map: {}
[03/15/18 12:31:10] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10] ERROR: unable to rename file: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm.part' -> 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm'
[03/15/18 12:31:10] ERROR: unable to rename file: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f137.mp4.part' -> 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f137.mp4'
[03/15/18 12:31:10] Traceback (most recent call last):
[03/15/18 12:31:10] Traceback (most recent call last):
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\downloader\common.py", line 201, in try_rename
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\downloader\common.py", line 201, in try_rename
[03/15/18 12:31:10] PermissionError: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm.part' -> 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm'
[03/15/18 12:31:10] PermissionError: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f137.mp4.part' -> 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f137.mp4'
[03/15/18 12:31:10] 
[03/15/18 12:31:10] 
[03/15/18 12:31:10] ERROR: [WinError 2] ÁöÁ¤µÈ ÆÄÀÏÀ» Ã£À» ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm'
[03/15/18 12:31:10] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10] Traceback (most recent call last):
[03/15/18 12:31:10] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 850, in process_ie_result
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 1623, in process_video_result
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 1970, in process_info
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 479, in run
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 182, in run_ffmpeg_multiple_files
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 182, in <genexpr>
[03/15/18 12:31:10] FileNotFoundError: [WinError 2] ÁöÁ¤µÈ ÆÄÀÏÀ» Ã£À» ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm'
[03/15/18 12:31:10] 
[03/15/18 12:31:10] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:31:10] ERROR: unable to rename file: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4.part' -> 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4'
[03/15/18 12:31:10] Traceback (most recent call last):
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\downloader\common.py", line 201, in try_rename
[03/15/18 12:31:10] PermissionError: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4.part' -> 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4'
[03/15/18 12:31:10] 
[03/15/18 12:31:10] ERROR: [WinError 2] ÁöÁ¤µÈ ÆÄÀÏÀ» Ã£À» ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4'
[03/15/18 12:31:10] Traceback (most recent call last):
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 850, in process_ie_result
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 1623, in process_video_result
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 1970, in process_info
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 479, in run
[03/15/18 12:31:10]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 182, in run_ffmpeg_multiple_files
[03/15/18 12:31:11]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\postprocessor\ffmpeg.py", line 182, in <genexpr>
[03/15/18 12:31:11] FileNotFoundError: [WinError 2] ÁöÁ¤µÈ ÆÄÀÏÀ» Ã£À» ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Yoga For Sleep ¢¾ Easy Bedtime Yoga _ 5 Minute Miracle.f137.mp4'
[03/15/18 12:31:11] 
[03/15/18 12:31:11] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:34:19] [debug] System config: []
[03/15/18 12:34:19] [debug] System config: []
[03/15/18 12:34:19] [debug] System config: []
[03/15/18 12:34:19] [debug] User config: []
[03/15/18 12:34:19] [debug] User config: []
[03/15/18 12:34:19] [debug] User config: []
[03/15/18 12:34:19] [debug] Custom config: []
[03/15/18 12:34:19] [debug] Custom config: []
[03/15/18 12:34:19] [debug] Custom config: []
[03/15/18 12:34:19] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=7CTsdbf81W8&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3&index=5']
[03/15/18 12:34:19] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=AYdQUS7jfPA&index=7&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3']
[03/15/18 12:34:19] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=DVabBY-NXRg&index=8&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3']
[03/15/18 12:34:19] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:34:19] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:34:19] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:34:19] [debug] youtube-dl version 2018.03.10
[03/15/18 12:34:19] [debug] youtube-dl version 2018.03.10
[03/15/18 12:34:19] [debug] youtube-dl version 2018.03.10
[03/15/18 12:34:19] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:34:19] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:34:19] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:34:19] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:34:19] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:34:19] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:34:19] [debug] Proxy map: {}
[03/15/18 12:34:19] [debug] Proxy map: {}
[03/15/18 12:34:19] [debug] Proxy map: {}
[03/15/18 12:34:19] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:34:20] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:34:20] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:34:46] [debug] System config: []
[03/15/18 12:34:46] [debug] User config: []
[03/15/18 12:34:46] [debug] Custom config: []
[03/15/18 12:34:46] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\owner\\Downloads\\%(title)s.%(ext)s', '-v', '--hls-prefer-native', '-v', 'https://www.youtube.com/watch?v=9wx_S6wiqOI&list=PLb09q0R7gAwQqAiRdBVmMpWL7JFwLMHN3&index=9']
[03/15/18 12:34:46] [debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[03/15/18 12:34:46] [debug] youtube-dl version 2018.03.10
[03/15/18 12:34:46] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[03/15/18 12:34:46] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/15/18 12:34:46] [debug] Proxy map: {}
[03/15/18 12:34:46] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:37:37] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:37:37] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:41:33] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/15/18 12:48:04] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[03/20/18 19:37:53] ERROR: ¿µ»ó ±Ç¸®ÀÚÀÇ ¿äÃ»À¸·Î
[03/20/18 19:37:53] Á¢¼ÓÇÏ½Å ±¹°¡¿¡¼­´Â ÇØ´ç ¿µ»óÀ» Àç»ýÇÒ ¼ö ¾ø½À´Ï´Ù.
[03/20/18 19:38:45] ERROR: ¿µ»ó ±Ç¸®ÀÚÀÇ ¿äÃ»À¸·Î
[03/20/18 19:38:45] Á¢¼ÓÇÏ½Å ±¹°¡¿¡¼­´Â ÇØ´ç ¿µ»óÀ» Àç»ýÇÒ ¼ö ¾ø½À´Ï´Ù.

```

#### What operating system do you use ?
window8.1
#### List of actions to perform to reproduce the problem:

  1. attempting to run as administrator
  2. remove and reinstall
 
  
#### What happens instead ?
Hello, I used it very well:)
But i have some problem...
I use window 8.1 and youtube-dlg 0.4
When i use this program, sometimes it can't download anything and appear [Errono 13]
Sometimes video downloads completely, but status is error.
Sometimes redownload continuously.

What should I do?

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

---

**Comment by nodiscc** [comment]
@apenfl456 Your problem seems to be that you are trying to download a video with a filename containing unicode characters on a filesystem that probably doesn't fully work with unicode filenames (NTFS? FAT?):

`[03/15/18 12:31:10] ERROR: unable to rename file: [WinError 32] ´Ù¸¥ ÇÁ·Î¼¼½º°¡ ÆÄÀÏÀ» »ç¿ë ÁßÀÌ±â ¶§¹®¿¡ ÇÁ·Î¼¼½º°¡ ¾×¼¼½º ÇÒ ¼ö ¾ø½À´Ï´Ù: 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm.part' -> 'C:\\Users\\owner\\Downloads\\Beginner Yoga ¢¾  Easy Morning Yoga For A Positive Mind.f251.webm'`

 * Try temporarily setting the output filename format in the options, to something that doesn't have the `title` field in it, and let us know if it works.
 * Does it work properly with videos that have no unicode characters in their title? (eg. https://www.youtube.com/watch?v=jHzbLNVhv-c)
