### ISSUE TITLE
youtube-dl-gui (youtube-dlg) doesn't download 720p mp4 with audio and video combined from youtube

### ISSUE THREAD

**Issue by IoanPaleru** [MrS0m30n3/youtube-dl-gui#292]
- [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

```
[04/02/18 15:18:07] [debug] System config: []
[04/02/18 15:18:07] [debug] User config: []
[04/02/18 15:18:07] [debug] Custom config: []
[04/02/18 15:18:07] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Computer User\\Downloads\\%(title)s.%(ext)s', '-x', '-f', '22', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y']
[04/02/18 15:18:07] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[04/02/18 15:18:07] [debug] youtube-dl version 2018.01.18
[04/02/18 15:18:07] [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[04/02/18 15:18:07] [debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg 3.3.2, ffprobe 3.3.2
[04/02/18 15:18:07] [debug] Proxy map: {}
[04/02/18 15:18:07] ERROR: requested format not available
[04/02/18 15:18:07] Traceback (most recent call last):
[04/02/18 15:18:07]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
[04/02/18 15:18:07]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
[04/02/18 15:18:07]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 1614, in process_video_result
[04/02/18 15:18:07] youtube_dl.utils.ExtractorError: requested format not available
[04/02/18 15:18:07] 
```

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

windows 7 home premium 64 bit

Youtube-dl-gui is a great program because it's easy to use, but how do you download a 720p mp4 with audio and video combined from youtube? When I selected Thanks.

**Comment by nodiscc** [comment]
@IoanPaleru Please post the program log after running an unsuccessful download.

**Comment by wildsprite** [comment]
this issue started for me about 8 days ago too. the only thing that appears after I try to do a download now is .m4a files and pic files(.jpg)
`[04/10/18 14:48:23] WARNING: video doesn't have subtitles
[04/10/18 14:48:23] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[04/10/18 14:50:51] WARNING: video doesn't have subtitles
[04/10/18 14:50:51] ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
[04/10/18 14:51:56] WARNING: video doesn't have subtitles
[04/10/18 14:51:56] ERROR: AtomicParsley was not found. Please install.`

if I download AtomicParsley is youtube-dlg going to need me to put it somewhere specific?

**Comment by IoanPaleru** [comment]
You should probably put "AtomicParsley.exe" in the same folder as "youtube-dl-gui.exe" if you're going to use it with youtube-dl-gui (youtube-dlg). If youtube-dl-gui (youtube-dlg) detects and uses atomicparsley automatically, then it should do everything for you, if not, then you can look at the read me file that comes with atomicparsley to figure out how to embed a .jpg picture into your .mp4 file.

To embed a .jpg picture into an .mp4 file with atomicparsley:

1. Navigate to the folder where "AtomicParsley.exe" is in
2. Press and hold the "shift" key on your keyboard, then while still pressing it, right-click with your mouse anywhere in the blank space of that folder, and select "open command window here"
3. A new "cmd.exe" (command prompt) window should have opened
4. You can now type:

AtomicParsley "C:/Computer User/Directory/Example.mp4" --artwork "C:/Computer User/Directory/Picture.jpg"

Note: Replace "C:/Computer User/Directory/Example.mp4" with the path to your .mp4 file, and "C:/Computer User/Directory/Picture.jpg" with the path to your .jpg file. Also, if your .jpg file actually has the .jpeg file extension, you'll have to change it to .jpg, or put .jpeg as the file extension in the command prompt window.

and press "enter"

5. AtomicParsley should now run, and create a new .mp4 file in the directory you're in, with the picture file you want to use as an album cover art merged into the .mp4 file

This is from atomicparsley's "Using AtomicParsley.rtf" read me file:

Example to set a picture file into your mpeg4 file (jpeg or png only):
AtomicParsley /path/your.m4a --artwork /path/to/your.jpg

I hope that helps, and let me know if you need any other help with it.

**Comment by user135711** [comment]
I'm having the same problem starting this week. I get only m4a or ogg files. 
My log file is a repeat of:
