### ISSUE TITLE
Error compiling from source

### ISSUE THREAD

**Issue by firestar9114** [MrS0m30n3/youtube-dl-gui#334]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
delete me and insert your log content here
```

#### What operating system do you use ?
Manjaro Linux

#### List of actions to perform to reproduce the problem:

  1. Download and extract the source code
  2. run "python setup.py install" from the installed folder location in the terminal
  3. Get the following output: 

```
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    from youtube_dl_gui import (
  File "/home/anonymous/Programs/youtube-dl-gui-0.4/youtube_dl_gui/__init__.py", line 25
    print error
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(error)?
```
I also tried the pip install and got the same message.
  
#### What is the expected behavior ?
I think it should compile and install

#### What happens instead ?
There appears to be a bug when attempting to compile

---

---

I can't install this program on my computer due to this issue at compilation.  It looks like it might simply be an issue of missing parenthesis according to the compiler error, so my suggested issue would be to try adding those in first.  I'm relatively new to Linux and not very savvy with the OS or python, but generally when I see an issue like that in c, c++, or c# debugging I just add the syntax and it works(semi-colons are the bane of my existence over in "C-land") but I loved this program back on windows, and it would be a shame if I can't get it working on Linux.  Hopefully this is a simple fix?  Thanks for taking the time to look into this.

-Firestar

**Comment by nodiscc** [comment]
> Missing parentheses in call to 'print'. Did you mean print(error)?
> python setup.py install

This is probably because the default python interpreter on Manjaro is python3, while youtube-dl-gui and its `setup.py` are python2. You can make sure of this by entering `python --version`

If python3 is the default, try to run `python2 setup.py install` or type `python<TAB><TAB>` to see available python interpreters on your machine.
