### ISSUE TITLE
Found a YT link what cannot download 

### ISSUE THREAD

**Issue by xuntan** [MrS0m30n3/youtube-dl-gui#338]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
delete me and insert your log content here
```

#### List of actions to perform to reproduce the problem:

  1. ..
  2. ..
  3. ..
  
#### What happens instead ?

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

---

**Comment by xuntan** [comment]
I found a link what youtube-dlg cannot download . It reports "Error" in dialog box. https://www.youtube.com/watch?v=Ir7pVCwFFj4  Other downloaders can donload it. 
Update:
While I am playing it in opera browser, the downloading was completed.
``` [09/18/18 13:57:00] ERROR: Signature extraction failed: Traceback (most recent call last):
[09/18/18 13:57:00] WARNING: Falling back on generic information extractor.
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[09/18/18 13:57:00] ERROR: Signature extraction failed: Traceback (most recent call last):
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[09/18/18 13:57:00] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[09/18/18 13:57:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsjdqsmfs\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[09/18/18 13:57:00]  (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[09/18/18 13:57:00] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[09/18/18 13:57:00]  (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[09/18/18 14:02:55] WARNING: video doesn't have subtitles
[09/18/18 14:04:34] WARNING: video doesn't have subtitles
[09/18/18 14:04:34] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[09/18/18 14:52:49] WARNING: video doesn't have subtitles
[09/18/18 14:52:49] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
 ```
