### ISSUE TITLE
Youtube-DLG not working on Windows 10 (tested with youtube links)

### ISSUE THREAD

**Issue by Akelun** [MrS0m30n3/youtube-dl-gui#341]
- [ ]    **I think** my problem is **NOT** with **youtube-dl**
  - [ X ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ X ] **I assure** that i am using the latest version of **youtube-dl**
  - [ X ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ X ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ (maybe) ] Bug report
- [ ]    Feature request (request for a new functionality)
- [ ]    Question
- [ X ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
delete me and insert your log content here

  -> There are nothing in the log content. The download stay at 0% and show the video file as "finished"

```

#### What operating system do you use ?

-> Windows 10 Pro - 64 bits

#### List of actions to perform to reproduce the problem:

  1. Open Youtube DLG on Windows 10
  2. Copy a youtube video link
  3. Paste it on Youtube-DLG
  4. Add
  5. Download
  
#### What is the expected behaviour ?

  It should download the video correctly (it was tested on the same computer with Windows 8.1 family - 64 bits before and it was working).

#### What happens instead ?

  It immediatly tells you the video has finished downloading while it is at 0% and there are no trace of any files in the folders

---

Screenshot: < https://sta.sh/0oysoigdggq >
![github - youtube dlg - issue win 10](https://user-images.githubusercontent.com/43582475/46030635-eddd6f00-c0f6-11e8-9149-431cb693ca67.png)

**Comment by zhanlaoban** [comment]
I have the same problem as you have.

**Comment by mon5termatt** [comment]
same is happening to me

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application

Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
`

**Comment by RuthlessRuler** [comment]
Youtube Has recently updated and so a Fix has been already rolled out to base youtube-dl, this One isnt updated yet!

**Comment by mon5termatt** [comment]
who updates this and how can we get in touch with him.

**Comment by cannbin** [comment]
Now  Daily Motion also has an error.

**Comment by Akelun** [comment]
Well, a friend of mine downloaded Youtube-DLG yesterday on his windows 10, tryed it, and it worked. So I once again redownloaded the Youtube-DLG programm and reinstalled it, and now it works for me. I didn't try for dailymotion though. Only for Youtube.

**Comment by realfasix** [comment]
>  It immediatly tells you the video has finished downloading while it is at 0% and there are no trace of any files in the folders

try to install vc++ runtime 2017
https://aka.ms/vs/15/release/vc_redist.x86.exe
https://aka.ms/vs/15/release/vc_redist.x64.exe

**Comment by zhanlaoban** [comment]
> > It immediatly tells you the video has finished downloading while it is at 0% and there are no trace of any files in the folders
> 
> try to install vc++ runtime 2017
> https://aka.ms/vs/15/release/vc_redist.x86.exe
> https://aka.ms/vs/15/release/vc_redist.x64.exe

Thx for your offering a solution, but, the issue still exists. I have already installed the vc++ runtime 2017 that you had given.

**Comment by SJongeJongeJonge** [comment]
I can confirm reinstalling works as I just did a fresh install yesterday, however this isn't necessary as there is a built-in update function.
If you click the settings icon it should download the latest version of youtube-dl.

**Comment by georgiMihalev** [comment]
Remember youtube-dl requires Python version 2.6, 2.7, or 3.2+ to work except for Windows exe.

Windows exe requires Microsoft Visual C++ 2010 Redistributable Package (x86) and does not require Python that is already embedded into the binary.

https://www.microsoft.com/en-US/download/details.aspx?id=5555
this solve problem for me

**Comment by helloqingfeng** [comment]
i have the same problem。it does not work。

> Exception in thread Thread-31:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 不是有效的 Win32

**Comment by clngr** [comment]
Same issue here on the portable version, everything updated.

**Comment by mbnoimi** [comment]
Same issue with portable version. Windows 10 updated to recent version and Python too (Python 2.7.16)

**Comment by pzprovi** [comment]
Win10
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

**Comment by dragonheirtw** [comment]
YOUTUBE-DL can run on Windows 10.
1. download youtube-dlg at https://mrs0m30n3.github.io/youtube-dl-gui/ 
2. run dlg and choose update then the new youtube-dl version will be downloaded automatically.
3. restart the app and enjoy it.

**Comment by erikburk** [comment]
If anyone still has this problem, I could solve it by pasting the normal command line youtube-dl files (youtube-dl.exe, ffmpeg.exe etc) to the youtube-dlg folder. It now works perfectly.

**Comment by explodingbee** [comment]
In response to dragonheirtw:  Thank you for providing that link.  It works very well and previously I was having error messages.

**Comment by explodingbee** [comment]
> YOUTUBE-DL can run on Windows 10.
> 
> 1. download youtube-dlg at https://mrs0m30n3.github.io/youtube-dl-gui/
> 2. run dlg and choose update then the new youtube-dl version will be downloaded automatically.
> 3. restart the app and enjoy it.

In response to dragonheirtw: Thank you for providing that link. It works very well and previously I was having error messages.

**Comment by riggedCoinflip** [comment]
I have the same problem. It works perfectly on my Laptop, but not my Desktop PC.
I used the download at  https://mrs0m30n3.github.io/youtube-dl-gui/
I have the runtimes, basically did everything - meaning I have the C++ 2010 runtime.
Reinstalled the program. But it doesnt work.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden

The error code translates to: The system couldnt find the file.

**Comment by axcore** [comment]
[Tartube](https://github.com/axcore/tartube) is a fork of youtube-dl-gui and works on MS Windows.

**Comment by toomanytoys** [comment]
I had the same problem on a Windows 10 (pro) machine.
Status always reported 'Finished'  and I got the 'Downloads Completed [OK]' window but nothing ever happened.
I had a more recent version of C++ 20XX runtime installed already.
Once I uninstalled that and put on C++ 2010 Redistributable Package it all worked perfectly.

**Comment by BW73** [comment]
Same here - update resolved it.

**Comment by AnnaSvensson91** [comment]
Youtube-dlg don t work on my new notebook, i have windows 10. I wanted to download some programm, not from youtube,i updated this programm many times, but it doesn t work. What can i do?

**Comment by axcore** [comment]
@AnnaSvensson91, try [Tartube](https://github.com/axcore/tartube) or [this fork](https://github.com/yt-dlg/yt-dlg).

**Comment by joaocarlosmormul** [comment]
so funciona no windows 7, instale o win 7 no virtual box e seja feliz.

**Comment by szanyij** [comment]
Installing vs2010 not solved the problem (problem: download finishes immediately without saving any data).
Solved by installing the runtimes from here: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported
both x86 and x64 versions of these are needed:
    Visual Studio 2015, 2017, 2019, and 2022
    Visual Studio 2013 (VC++ 12.0)
    Visual Studio 2012 (VC++ 11.0) Update 4
