### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by supersaiyansubtlety** [MrS0m30n3/youtube-dl-gui#354]
- [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
without `sudo`
```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    from youtube_dl_gui import (
  File "/Users/willlucic/Downloads/youtube-dl-gui-master/youtube_dl_gui/__init__.py", line 20, in <module>
    import gettext
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```
with `sudo`
```
sudo python setup.py install
Password:
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
No module named twodict
```

#### What operating system do you use ?
macOS
#### List of actions to perform to reproduce the problem:

  1. Download latest release
  2. Unarchive and open folder in terminal
  3. Attempt ot install
  
#### What is the expected behaviour ?
Successful installation
#### What happens instead ?
Failed installation, see logs

---

I get the above errors when following the installation instructions, the first when I enter `python setup.py install`, the second when I enter `sudo python setup.py install`

I've installed wxpython

**Comment by rhetr** [comment]
install [twodict](https://pypi.org/project/twodict/)

**Comment by biwin** [comment]
would be better if you add `install_requires` or something similar in setup.py
