### ISSUE TITLE
HearThis.at Downloads Producing Error

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#356]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [X] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[12/22/18 03:03:10] [debug] System config: []
[12/22/18 03:03:10] [debug] User config: []
[12/22/18 03:03:10] [debug] Custom config: []
[12/22/18 03:03:10] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Lewis\\Desktop\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://hearthis.at/djandyrivera/sea-shell-sessions-2017-final/']
[12/22/18 03:03:10] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[12/22/18 03:03:10] [debug] youtube-dl version 2018.12.17
[12/22/18 03:03:10] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[12/22/18 03:03:10] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[12/22/18 03:03:10] [debug] Proxy map: {}
[12/22/18 03:03:10] WARNING: unable to extract like count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

#### What operating system do you use ?
Windows 10
#### List of actions to perform to reproduce the problem:

  1. .. Insert HearThis.At link to a song
  2. .. Add, then start downloading
  3. .. Check finished product
  
#### What is the expected behaviour ?
For the download to complete, as normal, like with any other non-HearThis.at link.

#### What happens instead ?
The status changes to "Warning" the file is only a short 4 second clip, not a full download with the expected duration.

**Comment by nodiscc** [comment]
@groovybluedog does it work with the command-line [youtube-dl](https://rg3.github.io/youtube-dl/) tool?

**Comment by Shaharalynn** [comment]
Having issues with it completing the download. I keep getting an error. I reinstalled and also updated and still not sure what the issue is. I did do the steps to clear it that was in the post to see if it would work but no luck

[01/20/19 05:23:39] [debug] System config: []
[01/20/19 05:23:39] [debug] User config: []
[01/20/19 05:23:39] [debug] Custom config: []
[01/20/19 05:23:39] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\%(title)s-%(id)s-%(height)sp.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=ZjeYkrSVe8E']
[01/20/19 05:23:39] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[01/20/19 05:23:39] [debug] youtube-dl version 2018.12.17
[01/20/19 05:23:39] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[01/20/19 05:23:39] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[01/20/19 05:23:39] [debug] Proxy map: {}
[01/20/19 05:23:39] WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39] ERROR: Signature extraction failed: Traceback (most recent call last):
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1226, in _decrypt_signature
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1134, in _extract_signature_function
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1201, in _parse_sig_js
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\jsinterp.py", line 245, in extract_function
[01/20/19 05:23:39] youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39]  (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39] Traceback (most recent call last):
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1226, in _decrypt_signature
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1134, in _extract_signature_function
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1201, in _parse_sig_js
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\jsinterp.py", line 245, in extract_function
[01/20/19 05:23:39] youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39] Traceback (most recent call last):
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1226, in _decrypt_signature
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1134, in _extract_signature_function
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1201, in _parse_sig_js
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\jsinterp.py", line 245, in extract_function
[01/20/19 05:23:39] youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39] 
[01/20/19 05:23:39] During handling of the above exception, another exception occurred:
[01/20/19 05:23:39] 
[01/20/19 05:23:39] Traceback (most recent call last):
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\common.py", line 508, in extract
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1847, in _real_extract
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1236, in _decrypt_signature
[01/20/19 05:23:39] youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1226, in _decrypt_signature
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1134, in _extract_signature_function
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1201, in _parse_sig_js
[01/20/19 05:23:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\jsinterp.py", line 245, in extract_function
[01/20/19 05:23:39] youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39]  (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/20/19 05:23:39]
