### ISSUE TITLE
can't work on windows 10, need help

### ISSUE THREAD

**Issue by helloqingfeng** [MrS0m30n3/youtube-dl-gui#372]
**can't work and error is that:**

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 不是有效的 Win32

**Comment by tomtiao** [comment]
please update youtube-dl by using Update button in the top right menu.

**Comment by ravi7dce** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
