### ISSUE TITLE
can't download an hour long video =[

### ISSUE THREAD

**Issue by chickenpizza123** [MrS0m30n3/youtube-dl-gui#389]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ c] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ c] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```

[05/17/19 06:50:13] [debug] System config: []
[05/17/19 06:50:13] [debug] User config: []
[05/17/19 06:50:13] [debug] Custom config: []
[05/17/19 06:50:13] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\Videos\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=cB5jQeDQJsI']
[05/17/19 06:50:13] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[05/17/19 06:50:13] [debug] youtube-dl version 2019.03.01
[05/17/19 06:50:13] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[05/17/19 06:50:13] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[05/17/19 06:50:13] [debug] Proxy map: {}
[05/17/19 06:50:13] ERROR: cB5jQeDQJsI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[05/17/19 06:50:13] Traceback (most recent call last):
[05/17/19 06:50:13]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
[05/17/19 06:50:13]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 508, in extract
[05/17/19 06:50:13]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\youtube.py", line 1689, in _real_extract
[05/17/19 06:50:13] youtube_dl.utils.ExtractorError: cB5jQeDQJsI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[05/17/19 06:50:13] 

```

#### What operating system do you use ?
Wuindows 10 64 bit

#### List of actions to perform to reproduce the problem:

  1. ..Copy & pasting the link & trying to download the video gives an error
  2. ..
  3. ..
  
#### What happens instead ?

---

Trying to download an hour long video in it wont download :[

https://www.youtube.com/watch?v=cB5jQeDQJsI

**Comment by chickenpizza123** [comment]
nevermind its working now
