### ISSUE TITLE
Doens't accept unicode names

### ISSUE THREAD

**Issue by mbnoimi** [MrS0m30n3/youtube-dl-gui#39]
It doesn't work under Windows in case I pointed to Unicode names (whether folder name or video name). The log doesn't show any useful info I just get this:
````
[04/13/15 11:53:36] WARNING: There's no description to write.
````

You can test it using [this Arabic video](http://www.dailymotion.com/video/x2h0g6c_%D9%88%D8%AB%D8%A7%D8%A6%D9%82%D9%8A-royal-secrets-%D8%B3%D9%84%D8%B3%D9%84%D8%A9-%D8%B9%D9%85%D9%84%D9%8A%D8%A7%D8%AA-%D8%A5%D8%AD%D8%AA%D9%8A%D8%A7%D9%84-%D8%AF%D9%88%D9%84%D9%8A%D8%A9-1-12-%D9%88%D8%B5%D9%8A%D8%A9-%D8%A7%D9%84%D8%B3%D9%8A%D8%AF%D8%A9-%D8%A7%D9%84%D8%B9%D8%AC%D9%88%D8%B2_shortfilms) under DailyMotion (this bug occurs for YouTube too)
In case I pointed to Arabic folder name it failes to download. If I pointed to Latin folder name it download the file as following:
```
 Royal Secrets _      -1_12-   .mp4
```
While it should be as following:
```
 سلسلة عمليات إحتيال دولية -1/12- وصية السيدة العجوز.mp4
```

![2015-04-13_12-03-56](https://cloud.githubusercontent.com/assets/284547/7112717/35bb2790-e1d5-11e4-829e-c5168ae975bc.png)

**Comment by mbnoimi** [comment]
It seems this bug related to youtube-dl bug under Windows as mentioned in [this issue](https://github.com/rg3/youtube-dl/issues/5094)

**Comment by MrS0m30n3** [comment]
Hi, @mbnoimi 

First of all, if you try to download the same video using the **youtube-dl.exe** you still get the same result?  If yes can you please add the **-v** (verbose) option and paste the output here?

**Comment by mbnoimi** [comment]
@MrS0m30n3 the log please:

```
C:\Python 3.5\Scripts>youtube-dl.exe -v --newline -o G:\tmp\%(title)s.%(ext)s --
proxy http://127.0.0.1:8118/ -i --write-description http://www.dailymotion.com/v
ideo/x2h0g6c_%D9%88%D8%AB%D8%A7%D8%A6%D9%82%D9%8A-royal-secrets-%D8%B3%D9%84%D8%
B3%D9%84%D8%A9-%D8%B9%D9%85%D9%84%D9%8A%D8%A7%D8%AA-%D8%A5%D8%AD%D8%AA%D9%8A%D8%
A7%D9%84-%D8%AF%D9%88%D9%84%D9%8A%D8%A9-1-12-%D9%88%D8%B5%D9%8A%D8%A9-%D8%A7%D9%
84%D8%B3%D9%8A%D8%AF%D8%A9-%D8%A7%D9%84%D8%B9%D8%AC%D9%88%D8%B2_shortfilms
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--newline', '-o', 'G:\\tmp\\%(title)s.%(ext)s
', '--proxy', 'http://127.0.0.1:8118/', '-i', '--write-description', 'http://www
.dailymotion.com/video/x2h0g6c_%D9%88%D8%AB%D8%A7%D8%A6%D9%82%D9%8A-royal-secret
s-%D8%B3%D9%84%D8%B3%D9%84%D8%A9-%D8%B9%D9%85%D9%84%D9%8A%D8%A7%D8%AA-%D8%A5%D8%
AD%D8%AA%D9%8A%D8%A7%D9%84-%D8%AF%D9%88%D9%84%D9%8A%D8%A9-1-12-%D9%88%D8%B5%D9%8
A%D8%A9-%D8%A7%D9%84%D8%B3%D9%8A%D8%AF%D8%A9-%D8%A7%D9%84%D8%B9%D8%AC%D9%88%D8%B
2_shortfilms']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 3.5.0a3 - Windows-post2012Server-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {'https': 'http://127.0.0.1:8118/', 'http': 'http://127.0.0.1
:8118/'}
[dailymotion] x2h0g6c: Downloading webpage
[dailymotion] x2h0g6c: Extracting information
[dailymotion] x2h0g6c: Downloading embed page
WARNING: There's no description to write.
[debug] Invoking downloader on 'http://www.dailymotion.com/cdn/H264-848x480/vide
o/x2h0g6c.mp4?auth=1429130807-2562-bwfc690w-362d90e339a2f7154915a1d6a566f314'
[download] Resuming download at byte 7284256
[download] Destination: G:\tmp\?????? Royal Secrets _ ?????  ?????? ?????? ?????
 -1_12- ???? ?????? ??????.mp4
[download]   2.5% of 276.51MiB at 63.99KiB/s ETA 01:11:53
[download]   2.5% of 276.51MiB at 191.96KiB/s ETA 23:57
[download]   2.5% of 276.51MiB at 447.90KiB/s ETA 10:16
[download]   2.5% of 276.51MiB at 959.79KiB/s ETA 04:47
[download]   2.5% of 276.51MiB at 165.31KiB/s ETA 27:49
[download]   2.5% of 276.51MiB at 149.32KiB/s ETA 30:48
[download]   2.6% of 276.51MiB at 162.55KiB/s ETA 28:17
[download]   2.6% of 276.51MiB at 263.22KiB/s ETA 17:27
[download]   2.7% of 276.51MiB at 247.76KiB/s ETA 18:32
[download]   2.8% of 276.51MiB at 320.03KiB/s ETA 14:20
[download]   2.9% of 276.51MiB at 406.51KiB/s ETA 11:16
[download]   3.2% of 276.51MiB at 440.33KiB/s ETA 10:22

ERROR: Interrupted by user

C:\Python 3.5\Scripts>
```

**Comment by mbnoimi** [comment]
BTW, I used same exactly used parameters by youtube-dlg

**Comment by rb07** [comment]
Another use case (already mentioned in the youtube-dl thread): any user with a foreign character in its user name results in an early exception (the user's home directory is used to create/store something at the start of the program, and it fails; same thing happens when the program tries to create a log of the exception inside the installed location, which doesn't have write permission for the user -- no UTF problem here, just write permission, which is easy to fix).

This is in Windows so its probably lack of UTF-16 support.

**Comment by MrS0m30n3** [comment]
Hi @rb07 

That seems like a completely different problem. The main problem with the issue 4787 on the youtube-dl repo is the python's subprocess module on versions prior to 3. I was not able to reproduce your problem neither with the raw python version or the py2exe (Windows executable) version using foreign characters in the username path. Can you run the portable version of youtube-dlg from your desktop and paste the output of the log here?

**note**
Youtube-dlg creates the log file in the initialization process (See: [\__init\__.py:58](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/__init__.py#L58)) but i don't see a reason why this could fail if we use a config_path with foreign characters.

**Comment by rb07** [comment]
@MrS0m30n3

You misunderstood the log issue, I said the problem is a permission problem, not a UTF problem (i.e. foreign characters are not involved, actually not even tested since the path is `/Program Files/YoutubeDLG`).

Back on topic, the foreign character issue happened with the Windows executable, version 0.3.7, the original (not from the portable version, from the installed version) log:

`Traceback (most recent call last):`
`  File "__main__.py", line 35, in <module>`
`  File "youtube_dl_gui\__init__.pyc", line 52, in <module>`
`  File "youtube_dl_gui\utils.pyc", line 93, in get_config_path`
`  File "ntpath.pyc", line 84, in join`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 8: ordinal not in range(128)`

**Comment by MrS0m30n3** [comment]
@rb07 

This was a completely different issue. Anyway, the problem was in the joining process as you can see in your log file, i just had to decode the imported value from the os.getenv function using the system preferred encoding. You should not longer face this issue as long as your system encoding can handle the foreign characters (See: https://github.com/MrS0m30n3/youtube-dl-gui/commit/def80ed6b419ff121a6284fd9ea402af3cf95386 for more details). 


You can find the patched portable version [here](https://drive.google.com/file/d/0B4LUjPpAKNa1TUNaeWRIeFpUS0k/view?usp=sharing).
Can you give it a try an let me know if that worked?

**Comment by rb07** [comment]
@MrS0m30n3

Tested the patched portable version, same problem, see the log:

`Traceback (most recent call last):`
`  File "youtube-dl-gui", line 35, in <module>`
`  File "youtube_dl_gui\__init__.pyc", line 54, in <module>`
`  File "youtube_dl_gui\optionsmanager.pyc", line 51, in __init__`
`  File "youtube_dl_gui\optionsmanager.pyc", line 201, in load_default`
`  File "ntpath.pyc", line 310, in expanduser`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 10: ordinal not in range(128)`

**Comment by MrS0m30n3** [comment]
@rb07 I opend a new issue for this problem check: #57

**Comment by MrS0m30n3** [comment]
### Summary (work in progress)

Problem occurs in Python 2.* because the C implementation of the subprocess module can't handle unicode (http://bugs.python.org/issue1759845).

1. **youtube-dlg** uses subprocess to spawn a **youtube-dl** process
2. **youtube-dl** uses subprocess to spawn a **ffmpeg** process (https://github.com/rg3/youtube-dl/issues/4787)

---

#### (1.) youtube-dlg -> youtube-dl
* **Youtube-dlg** does not yet support Python 3.*
* On OS's that use UTF-8 (e.g. Linux) we can encode the unicode parameters at the **youtube-dlg** side and let the **youtube-dl** decode them at the other end without losing any characters
* The above solution does not work on Windows since they use encodings like cp1252, cp437, etc, that can't handle unicode characters (Windows suck!!!)
* On Windows we need a way to encode the unicode parameters at the **youtube-dlg** side using UTF-8 (we have that) and decode them at the **youtube-dl** side again using UTF-8 (we dont have that, see https://github.com/rg3/youtube-dl/issues/6119)

#### (2.) youtube-dl -> ffmpeg
* Can be solved if we use a Python 3.* **youtube-dl** binary to do our job (https://github.com/rg3/youtube-dl/issues/5094)
* Also check https://github.com/rg3/youtube-dl/issues/5527

**Comment by mbnoimi** [comment]
After years of waiting it seems this bug still occurs

**Comment by elico** [comment]
@MrS0m30n3 How can someone resolve this bug?

**Comment by mbnoimi** [comment]
> @MrS0m30n3 How can someone resolve this bug?

This project no longer maintained so I currently use https://github.com/axcore/tartube it's full of advanced options in addition to the classic ui
