### ISSUE TITLE
Cannot Download Videos

### ISSUE THREAD

**Issue by Rexor26** [MrS0m30n3/youtube-dl-gui#397]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
There's nothing on the log content
```

#### What operating system do you use ?

Windows 10 64 bit

#### List of actions to perform to reproduce the problem:

  1. Copy and paste desired URL
  2. Download
  3. After few seconds of queuing, download status shows "error" at 0% and "download complete"
  
#### What is the expected behaviour ?

Video starts downloading (progress bar)

#### What happens instead ?

Status shows "error" and dialog box shows "download complete"

#### What operating system do you use ?

Windows 10 64 bit 

---

I tried downloading from Youtube, DailyMotion and even Pornhub (plus other sites). Results still the same.

**Comment by LittleDaoist** [comment]
Just tried downloading a couple of videos from youtube and it works.

**Comment by Efreak** [comment]
Confirmed on **Windows 10 Pro 64-bit**
<details>
<summary>winver.exe screenshot</summary>

![image](https://user-images.githubusercontent.com/749751/62899473-5e10d580-bd47-11e9-8562-c62467be996e.png)

</details>

Youtube-DLG installer does set directory permisions, so it cannot access the default location for the log file (this should be changed), and therefore the log is empty.

<details>
<summary>log error screenshot</summary>

![image](https://user-images.githubusercontent.com/749751/62899785-150d5100-bd48-11e9-9e7e-c0861773dfad.png)

</details>

After creating an empty file and adding the correct permissions to it *(to avoid this, create it elsewhere and then move it)*, the log window still refuses to display, and instead I get the following in the log file:

<details>
<summary>contents of youtube-dl-gui.exe.log</summary>

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
```

</details>

**Comment by liamengland1** [comment]
This project is abandoned.

**Comment by Efreak** [comment]
well, if it helps anyone else, I can confirm that youtube-dl.exe isn't being downloaded correctly. Download [youtube-dl.exe](https://yt-dl.org/downloads/2019.08.02/youtube-dl.exe) from [the official site](https://ytdl-org.github.io/youtube-dl/download.html) and save it to `%appdata%\youtube-dlg\youtube-dl.exe`, and it will work fine.

**Comment by coasterfr** [comment]
> 
> 
> well, if it helps anyone else, I can confirm that youtube-dl.exe isn't being downloaded correctly. Download [youtube-dl.exe](https://yt-dl.org/downloads/2019.08.02/youtube-dl.exe) from [the official site](https://ytdl-org.github.io/youtube-dl/download.html) and save it to `%appdata%\youtube-dlg\youtube-dl.exe`, and it will work fine.

thank you

**Comment by thirdwheel** [comment]
For future reference, I had to install the Visual C++ 2010 redistributables before it would work for me.
