### ISSUE TITLE
Youtube -dlg does not install on the new version of Ubuntu 20.04

### ISSUE THREAD

**Issue by serial02** [MrS0m30n3/youtube-dl-gui#425]
Hello Team @philipzae 

Youtube -dlg no longer installs on the new version of Ubuntu 20.04.

When upgrading from Ubuntu 20.04 it is removed

Could you please check this case and see what changes are needed?

I used all the tips found on the internet and still don't install it anymore.

I thank you for your attention

Edson Santos

**Comment by aplatypus** [comment]
Hi -- Actually Youtube-DLG did not install for me using `pip` on Ubuntu 19.10 either.  Note that these two Ubuntus are Python 3 (no Python 2 by default).

Regarding Ubuntu 20.04, there is no PPA support for `Youtube-DLG` for Ubuntu 19.10, so it may be the same issue for Ubuntu 20.

Here's the error report from `pip insall`.  I am hoping this is something that can be repaired simply.

```
  $ pip3 install youtube-dlg
Collecting youtube-dlg
  Using cached https://files.pythonhosted.org/packages/55/28/70620c1ffb8ad7ecb81913a053dc454ad7116d3fbdbd8ca23ac0b19ebb40/Youtube-DLG-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hyeei0o1/youtube-dlg/setup.py", line 69, in <module>
        from youtube_dl_gui import (
      File "/tmp/pip-install-hyeei0o1/youtube-dlg/youtube_dl_gui/__init__.py", line 25
        print error
                  ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(error)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hyeei0o1/youtube-dlg/
```
