### ISSUE TITLE
Youtube always fails on mp4 1080p or 720p download "youtube_dl.utils.ExtractorError: requested format not available"

### ISSUE THREAD

**Issue by Moltresrider** [MrS0m30n3/youtube-dl-gui#438]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [X ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X ] **I assure** that i am using the latest version of **youtube-dl**
  - [ X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [X ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[03/30/20 21:12:26] [debug] System config: []
[03/30/20 21:12:26] [debug] User config: []
[03/30/20 21:12:26] [debug] Custom config: []
[03/30/20 21:12:26] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Arceist Justin\\%(title)s.%(ext)s', '-f', '37', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=hNqtfFXq00k']
[03/30/20 21:12:26] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[03/30/20 21:12:26] [debug] youtube-dl version 2020.03.24
[03/30/20 21:12:26] [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[03/30/20 21:12:26] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/30/20 21:12:26] [debug] Proxy map: {}
[03/30/20 21:12:26] ERROR: requested format not available
[03/30/20 21:12:26] Traceback (most recent call last):
[03/30/20 21:12:26]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
[03/30/20 21:12:26]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
[03/30/20 21:12:26]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1636, in process_video_result
[03/30/20 21:12:26] youtube_dl.utils.ExtractorError: requested format not available
[03/30/20 21:12:26] 
```

#### What operating system do you use ?
Windows 7
#### List of actions to perform to reproduce the problem:

  1. .. Select "mp4 1080p or mp4 720p" from the drop down list
  2. .. Copy a URL to a Youtube video THAT DOES have 720p and 1080p available
  3. .. click download and watch YouTube DLG instantly fail to download the file
  
#### What is the expected behaviour ?
YouTube DLG should download the video
#### What happens instead ?
nothing but "error" every time/every video

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

Windows 7
---

Any time I try to download a video in 720p or 1080p, YouTube DLG always fails with "error". YouTube DLG **no longer** downloads videos in HD by default (downloading them in 360p instead) and manually selecting any HD mp4 option always fails

**Comment by SasquatchYuja** [comment]
You say that the videos you are trying to download do have mp4 720/1080p.
However, it really looks like from the output that they do not : this is exactly the error you have with CLI youtube-dl when you try to fetch an absent format.
The URL in your example actually has the said formats that you want, and I could successfully download them, can you provide more faulty URLs ?

**Comment by sentix001** [comment]
im having exact same issue ERROR: requested format not available

https://www.youtube.com/watch?v=ErPsyBUCijM

take a look at this

1080p available i check manually on youtube site

downloading mp4 only or webm only works but downloads 720p 

but selecting 1080p of both webm and avi from the list breaks and shows that error

**Comment by axcore** [comment]
Make sure FFmpeg is installed on your system.

**Comment by HyroGoth** [comment]
Hey, idk if someone will see this but i tried download 1080p and i have FFmpeg installed

![image](https://user-images.githubusercontent.com/113087198/220802304-f734df38-b274-4511-ae20-c1213959588f.png)
![image](https://user-images.githubusercontent.com/113087198/220802348-57a2a90e-e850-4aed-9619-e40b06cb6a5e.png)
![image](https://user-images.githubusercontent.com/113087198/220802390-ff9e0ec1-738a-4497-932e-dfa924720d91.png)
![image](https://user-images.githubusercontent.com/113087198/220802621-12ee836f-f00a-4f79-93d7-53c8a40231ad.png)
