### ISSUE TITLE
Youtube-DLG does not download playlist

### ISSUE THREAD

**Issue by ducman1611** [MrS0m30n3/youtube-dl-gui#442]
### What is the purpose of your *issue*?

- [x ] Bug report
- [ ] Feature request (request for a new functionality)
- [] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[04/12/20 13:00:33] [debug] System config: []
[04/12/20 13:00:33] [debug] User config: []
[04/12/20 13:00:33] [debug] Custom config: []
[04/12/20 13:00:33] [debug] Command-line args: ['--newline', '--playlist-start', '2', '-R', '20', '-i', '-o', 'C:\\Users\\12745384\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/playlist?list=LLUw7I9FO85uTW8GSgK8DuRA']
[04/12/20 13:00:33] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[04/12/20 13:00:33] [debug] youtube-dl version 2020.03.24
[04/12/20 13:00:33] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[04/12/20 13:00:33] [debug] exe versions: none
[04/12/20 13:00:33] [debug] Proxy map: {}
[04/12/20 13:00:33] ERROR: This playlist does not exist.
[04/12/20 13:00:33] Traceback (most recent call last):
[04/12/20 13:00:33]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
[04/12/20 13:00:33]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
[04/12/20 13:00:33]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\youtube.py", line 2762, in _real_extract
[04/12/20 13:00:33]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\youtube.py", line 2685, in _extract_playlist
[04/12/20 13:00:33] youtube_dl.utils.ExtractorError: This playlist does not exist.
[04/12/20 13:00:33] 

```

#### What operating system do you use ?
Window 10 64 bit
#### List of actions to perform to reproduce the problem:

  1. Copy the link to my liked video playlist
  2. Click Add
  3. Pres download
  
#### What is the expected behaviour ?
Download all videos or mp3
#### What happens instead ?
Error. the log says The playlist does not exist

**Comment by ducman1611** [comment]
Is this because the number of videos in this playlist is too high? there are 1004 videos

**Comment by axcore** [comment]
I get the same error when I use [that link](https://www.youtube.com/playlist?list=LLUw7I9FO85uTW8GSgK8DuRA) in a web browser. It's not a youtube-dlg problem.

**Comment by ducman1611** [comment]
I think it is because this is a private playlist. they are the videos which I liked. Would the be a way to overcome this?

**Comment by axcore** [comment]
Make the list public, download the videos, then make the list private again.

**Comment by ducman1611** [comment]
I tried but I cannot make the Liked Videos playlist public
