### ISSUE TITLE
I keep getting error "Youtube-dl download failed [<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>]" when trying to update Youtube-DLG

### ISSUE THREAD

**Issue by Teutowolf** [MrS0m30n3/youtube-dl-gui#461]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden
```

#### List of actions to perform to reproduce the problem:

  1. ..
  2. ..
  3. ..
  
#### What is the expected behaviour ?
I'm trying to update youtube-dlg after installing everything, since I got a new PC and everything worked wonderfully.
#### What happens instead ?
It immediately gives me the error "Youtube-dl download failed [<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>]".
I've already tried adding "--no-check-certificate" in options with no success.
---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Win10

---

When trying to update it immediately gives me the error "Youtube-dl download failed [<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>]".
I've already tried adding "--no-check-certificate" in Options>Extra with no success.
YT downloads don't work either. And yes, I'm aware there is a similar topic created already, but that didn't help me and it's closed.

**Comment by ghost** [comment]
This is an issue on their side. I've been trying to get this to work for a week.
I'm also on a fresh install of Windows, and nothing about this program works properly.
I had to install YTDL from another source and manually set it up for the program to even work, and even then it doesn't finish converting properly.

Someone needs to make an alternative.
I had the EXACT issue as you, there's no solution anywhere and the other issues mentioning it get closed.
Tartube doesn't work well and is overly convoluted.

**Comment by axcore** [comment]
> Someone needs to make an alternative.

Why don't you go ahead and do it yourself?

**Comment by Teutowolf** [comment]
> 
> 
> This is an issue on their side. I've been trying to get this to work for a week.
> I'm also on a fresh install of Windows, and nothing about this program works properly.
> I had to install YTDL from another source and manually set it up for the program to even work, and even then it doesn't finish converting properly.
> 
> Someone needs to make an alternative.
> I had the EXACT issue as you, there's no solution anywhere and the other issues mentioning it get closed.
> Tartube doesn't work well and is overly convoluted.

Glad to hear I'm not the only one. Hopefully they'll fix this soon if it's not on my end. 
Never heard of Tartube but I'll give it a shot.

**Comment by axcore** [comment]
@Teutowolf, this project is not being updated any more, so don't look forward to a fix. Tartube is [here](https://github.com/axcore/tartube) if you want to try it.

**Comment by Teutowolf** [comment]
@axcore I tried downloading a video in classic mode in .mp3 but it gives me an error saying "ERROR: requested format not available"

**Comment by ghost** [comment]
> > Someone needs to make an alternative.
> 
> Why don't you go ahead and do it yourself? The first working release of Tartube only took me five or six weeks, and that _includes_ the time spent learning Python.

Because I'm a consumer. Nobody cares how long it took you btw, leave the humblebrags out when this is a place to tell you that your shit sucks.

**Comment by axcore** [comment]
@Teutowolf In the Classic Mode tab, the format selector is broken in v2.1.051. You can use [this workaround](https://github.com/axcore/tartube/issues/124#issuecomment-656277975) or install v2.1.0 instead.

**Comment by axcore** [comment]
> Because I'm a consumer.

Ah, so you are waiting for someone else to do all of the work that you can't be bothered to do yourself.

I hope it's not too long a wait.

**Comment by fourpoint7** [comment]
> 
> 
> > > Someone needs to make an alternative.
> > 
> > 
> > Why don't you go ahead and do it yourself? The first working release of Tartube only took me five or six weeks, and that _includes_ the time spent learning Python.
> 
> Because I'm a consumer. Nobody cares how long it took you btw, leave the humblebrags out when this is a place to tell you that your shit sucks.

While it is true that tools and services are not above reproach and constructive criticism, you are not in the position to speak for everyone so please [check the attitude at the door.](https://docs.github.com/en/github/site-policy/github-community-guidelines) It's clear if you read what is being said that it is not boasting, but simply conveying the sense of time and effort that it took to develop the program. Given your response, I'm sure you would not react well if someone had said what you've said about a personal project you worked on, would you? It's not a constructive attitude to have, and definitely does not encourage the person you're talking with to help. 

If anything, direct your frustration at the media companies who make tools like youtube-dl desired by people (necessary, IMO) by forcing many asinine restrictions on content.

Yeah, life's tough and it sucks for a lot of people right now. Please be more compassionate and charitable. All this unprovoked hostility is way out of bounds and unnecessary.

**Comment by axcore** [comment]
@Teutowolf By the way, the broken selector is fixed. I haven't created new installers yet, but you can download the source code from here or from PyPI.

**Comment by comsomisha** [comment]
You should delete expired intermediate certificates for Windows 10. See https://github.com/ytdl-org/youtube-dl/issues/7309#issuecomment-172354527.

**Comment by LesterCovax** [comment]
> > Because I'm a consumer.
> 
> Ah, so you are waiting for someone else to do all of the work that you can't be bothered to do yourself.
> 
> I hope it's not too long a wait.

I'd love for someone to make a documentary on OSS, its devs/maintainers, and the amount of time/stress it entails.  Devs used to have the sanctuary of BBS, listserv, or CVS/SVN to shield them, but as VCS/ALM tools have evolved it also reduced the distance between them and ignorant users.  The amount of unrewarded/underappreciated time put into OSS, and the swelling potential for dev burnout is an increasing issue IMO.

Admittedly, i'll curse when I come across an abandoned software project I relied on, and then have to remind myself that I've abandoned popular projects with no warning myself.  There's an org/repo I came across a while ago that helps thwart this paradigm by letting a dev request that someone take over as maintainer, kind of like a payless job board (been meaning to post there myself).  Wouldn't be a bad idea for GitHub to help streamline that process by encouraging stale repo owners to hand the keys over to someone else if there's still devs willing to work on a project, as few people know how to look for active forks.
`/raaaaaant`

<img src="https://user-images.githubusercontent.com/34850610/88446782-f8541700-cdfa-11ea-99b8-d7c78e064d0e.gif" width=200px />

**Comment by negativecitizen** [comment]
I' ve a definitive solution to this .You can redirect  the download directory for youtube-dl to avoid this error :1.  first locate your "settings.json" usually in  "C:\Users\<your user>\AppData\Roaming\youtube-dlg" 2. edit the last line ("youtubedl_path".............. ")
  and change the path  to something practical like C:\\youtube-dl  3. paste the latest  youtube-dl.exe   downloaded from this  url  https://github.com/ytdl-org/youtube-dl/releases/  
Probably you need to make the copy a a fresh .exe  time to time to get the latest version but  its straight and works. 
This is a way to  manually update the library avoiding  the certificate error and the lost of time .Enjoy

**Comment by negativecitizen** [comment]
Seems that installing internet explorer 11 fix also the problem.
