### ISSUE TITLE
Getting "Downloads complete" message and errors

### ISSUE THREAD

**Issue by IArnaut2** [MrS0m30n3/youtube-dl-gui#466]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

### Bug report

I've tried downloading few videos from YouTube. I've entered a video link to the download list and started downloading, But I was told that downloads are complete and got error messages. It happens when trying to download some videos.

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
2. Go to `Options -> Extra` tab
3. Enable **Debug youtube-dl**
4. Go to `Options -> Advanced` tab and **Clear** your log content
5. Try to download the URL
6. Copy the **whole** log content and insert it between the ``` part below
```
[08/05/20 18:27:00] [debug] System config: []
[08/05/20 18:27:00] [debug] User config: []
[08/05/20 18:27:00] [debug] Custom config: []
[08/05/20 18:27:00] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Igor\\Videos\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=C1d8sRMI8_w']
[08/05/20 18:27:00] [debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[08/05/20 18:27:00] [debug] youtube-dl version 2020.05.03
[08/05/20 18:27:00] [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[08/05/20 18:27:00] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[08/05/20 18:27:00] [debug] Proxy map: {}
[08/05/20 18:27:00] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[08/05/20 18:27:00] Traceback (most recent call last):
[08/05/20 18:27:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
[08/05/20 18:27:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
[08/05/20 18:27:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\youtube.py", line 2394, in _real_extract
[08/05/20 18:27:00]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
[08/05/20 18:27:00] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[08/05/20 18:27:00] 
```

#### What operating system do you use ?

Windows 7 Pro 64-Bit

#### List of actions to perform to reproduce the problem:

1. Paste video URL.
2. Add to the list.
3. Choose file type.
4. Click download button.
  
#### What is the expected behaviour ?

Video to be downloaded.

#### What happens instead ?

Gets a window that says that downloads are complete, but downloads error.

**Comment by axcore** [comment]
This project is not being maintained any more. You could try [this fork](https://github.com/axcore/tartube) instead.

**Comment by NanoCats** [comment]
> This project is not being maintained any more. You could try [this fork](https://github.com/axcore/tartube) instead.

From what I can gather Tartube only does video files and you can't just grab mp3s which greatly diminishes its usefulness.

**Comment by axcore** [comment]
You might be referring to https://github.com/axcore/tartube/issues/124, in which the format selector on the Classic Mode tab was broken. It was fixed in v2.1.057.

Apart from that, Tartube re-uses the youtube-dl-gui code, so it can do everything that youtube-dl-gui can do.
