### ISSUE TITLE
NRK still does not work

### ISSUE THREAD

**Issue by TheNorwegian** [MrS0m30n3/youtube-dl-gui#490]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[12/05/20 21:50:45] [debug] System config: []
[12/05/20 21:50:45] [debug] User config: []
[12/05/20 21:50:45] [debug] Custom config: []
[12/05/20 21:50:45] [debug] Command-line args: ['--newline', '-i', '--write-sub', '-o', 'E:\\Mediadisk\\DTV og DVD\\nett-tv\\%(title)s.%(ext)s', '--sub-lang', 'sv', '-v', '--ignore-config', '--hls-prefer-native', 'https://tv.nrk.no/serie/white-wall/sesong/1/episode/1/avspiller']
[12/05/20 21:50:45] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[12/05/20 21:50:45] [debug] youtube-dl version 2020.12.05
[12/05/20 21:50:45] [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[12/05/20 21:50:45] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[12/05/20 21:50:45] [debug] Proxy map: {}
[12/05/20 21:50:45] ERROR: NRK said: Ikke tilgjengelig utenfor Norge
[12/05/20 21:50:45] Traceback (most recent call last):
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\common.py", line 532, in extract
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\nrk.py", line 164, in _real_extract
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\nrk.py", line 109, in _extract_from_playback
[12/05/20 21:50:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\nrk.py", line 48, in _raise_error
[12/05/20 21:50:45] youtube_dl.utils.ExtractorError: NRK said: Ikke tilgjengelig utenfor Norge
[12/05/20 21:50:45] 
```

#### What operating system do you use ?
Win 7

#### List of actions to perform to reproduce the problem:

  1. .. paste url into YT-DLG
  2. .. try to download
  3. ..
  
#### What is the expected behaviour ?
Pre-Processing starts and then downloading should start

#### What happens instead ?
Pre-processing starts but the download does not start at all, resulting in an error message: "error" in the status field.

---

---

NRK.no downloadads stopped working (at least for me) in the summer and it has been months now without downloads working. This may have been mentioned elsewhere before but as NRK.no downloads were stable before, I assumed it would be looked into and reinstated, but it does not seem like so.

**Comment by axcore** [comment]
This is a youtube-dl issue, not a youtube-dl-gui.

Downloads from nrk.no are working for me. When was the last time you updated youtube-dl?

This project is not maintained any more. There is an active fork [here](https://github.com/axcore/tartube).

**Comment by axcore** [comment]
I think it's not possible. Tartube loads the config file once, when it starts. Tartube could import a config file, but could not load it. And when Tartube closes, it saves a new config file, so the imported config file is destroyed.

**Comment by TheNorwegian** [comment]
I updated youtube-dl yesterday, and two before that, and weekly before that, ever since the problem started this summer.

Apologies for the wrong forum.
