### ISSUE TITLE
Youtube-DL GUI issues

### ISSUE THREAD

**Issue by kostasall12** [MrS0m30n3/youtube-dl-gui#499]
Hello.

I have recently Installed windows 8.1 pro on my laptop (after formatting hard drive) but Youtube-DL GUI isn't working. (before formatting hard drive, Youtube-DL GUI worked fine)

**FIRST ISSUE.** When trying to update it immediately gives me the error "Youtube-dl download failed [<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed [(_ssl.c:661)>]".]

I've already tried adding "--no-check-certificate" in Options>Extra with no success.  

**SECOND ISSUE.** I've installed the Microsoft Visual C++ 2010 x86 Redistributable and I'm running youtube-dl-gui.exe as admin. Once I enter the url(s) they get queued but nothing after that happens. When I close Youtube-DL GUI, I receive this message

The logfile (youtube-dl-gui.exe.log) produces such a message:  

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] 

**EDIT: I did it manually and now works.**

**Comment by axcore** [comment]
youtube-dl-gui is not being maintained any more. There are various forks around, including [this one](https://github.com/axcore/tartube).
