### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by KOT040188** [MrS0m30n3/youtube-dl-gui#501]
When trying to install, I get this error:
```
kot@192:~$ pip install youtube-dlg
Defaulting to user installation because normal site-packages is not writeable
Collecting youtube-dlg
  Downloading Youtube-DLG-0.4.tar.gz (153 kB)
     |████████████████████████████████| 153 kB 2.4 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uigeedb4/youtube-dlg/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uigeedb4/youtube-dlg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ehhjazge
         cwd: /tmp/pip-install-uigeedb4/youtube-dlg/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uigeedb4/youtube-dlg/setup.py", line 69, in <module>
        from youtube_dl_gui import (
      File "/tmp/pip-install-uigeedb4/youtube-dlg/youtube_dl_gui/__init__.py", line 25
        print error
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(error)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



```
Opensuse tumbleweed.

**Comment by axcore** [comment]
This project is abandoned, and cannot easily be installed on modern Linux distributions. Try [this fork](https://github.com/oleksis/youtube-dl-gui) or [this one](https://github.com/axcore/tartube).

**Comment by gormih** [comment]
This source code for python version 2. Incompatible with Python3.

**Comment by KOT040188** [comment]
What am I to do now?

**Comment by axcore** [comment]
Use one of the forks I suggested.

youtube-dl-gui is written in Python 2. Most Linux distributions no longer provide Python 2, so it's not easy to install youtube-dl-gui on any of them.

**Comment by gormih** [comment]
> Use one of the forks I suggested.
> 
> youtube-dl-gui is written in Python 2. Most Linux distributions no longer provide Python 2, so it's not easy to install youtube-dl-gui on any of them.

Most Linux distributions  provide Python 2. For example, on Debian and Ubuntu python 2 is by default!

**Comment by axcore** [comment]
> Most Linux distributions provide Python 2. For example, on Debian and Ubuntu python 2 is by default!

I meant to write: "Most Linux distributions no longer provide Python 2 support", which means that software written in python 2 is no longer available in software repositories.

**Comment by gormih** [comment]
> > Most Linux distributions provide Python 2. For example, on Debian and Ubuntu python 2 is by default!
> 
> I meant to write: "Most Linux distributions no longer provide Python 2 support", which means that software written in python 2 is no longer available in software repositories.

[Really ](https://packages.debian.org/sid/python/python2) ? 
Why do you mislead people?! 
Do you really think that no one knows how to use search engines and are completely stupid?

**Comment by axcore** [comment]
My friend, you are mistaken. The removal of all python2  modules from Debian was [announced in 2019](https://lists.debian.org/debian-python/2019/07/msg00080.html). youtube-dl-gui has already been removed, or is due to be removed, from most Linux distributions (for example, it was removed from Mageia just [one week ago](https://wiki.mageia.org/en/Mageia_8_Release_Notes)).

If you have an unhappy life, by all means call everyone else stupid. Perhaps it will make you feel better. But perhaps you have noticed that I have uploaded over half a million lines of code to Github, whereas you have uploaded only a few hundred lines. I think that you need to choose a different insult.
