### ISSUE TITLE
.... what

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#515]
Traceback (most recent call last):
  File "/home/jayjames/tmp/youtube-dl-gui/setup.py", line 73, in <module>
    from youtube_dl_gui import (
  File "/home/jayjames/tmp/youtube-dl-gui/youtube_dl_gui/__init__.py", line 26
    print error
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(error)?

**Comment by axcore** [comment]
You are trying to run a Python2 application using Python3.

This project is abandoned, try [this fork](https://github.com/oleksis/youtube-dl-gui) or [this one](https://tartube.sourceforge.io/).
