### ISSUE TITLE
Unable to extract uploader ID

### ISSUE THREAD

**Issue by Hyper-Nov4** [MrS0m30n3/youtube-dl-gui#553]
### What is the purpose of your *issue*?

- [x] Bug report

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[05/16/23 18:22:34] [debug] System config: []
[05/16/23 18:22:34] [debug] User config: []
[05/16/23 18:22:34] [debug] Custom config: []
[05/16/23 18:22:34] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\shagg\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=aLDNYJLO5UM']
[05/16/23 18:22:34] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[05/16/23 18:22:34] [debug] youtube-dl version 2021.12.17
[05/16/23 18:22:34] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[05/16/23 18:22:34] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[05/16/23 18:22:34] [debug] Proxy map: {}
[05/16/23 18:22:34] ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[05/16/23 18:22:34] Traceback (most recent call last):
[05/16/23 18:22:34]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
[05/16/23 18:22:34]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
[05/16/23 18:22:34]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
[05/16/23 18:22:34]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
[05/16/23 18:22:34]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
[05/16/23 18:22:34] youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[05/16/23 18:22:34] 
```

#### What operating system do you use ?

windows 10 x64bit

#### List of actions to perform to reproduce the problem:

  1. .. upload youtube url to the box
  2. ..  click add
  3. .. click start
  
#### What is the expected behaviour ?
The video should download to the folder i selected
#### What happens instead ?
queues, starts the download but before any actual downloading begins switches to a error.

![image](https://github.com/MrS0m30n3/youtube-dl-gui/assets/123339146/13bdce0a-10a7-4774-8906-5a293022630a)

**i have litteraly never used github in my life and have no clue how to use python, so please bare with me here and if i really messed up some formatting or something just idk dm me on discord for more info since i respond quick: nov4#8008**

**Comment by Phat32** [comment]
I had the same issue and just figured out the solution

Go to the youtube-dlg folder in your AppData:
%appdata%\youtube-dlg

From here you can do 1 of 2 things:

- Replace the youtube-dl.exe with a new updated version from the official repo. This will fix it right now and be done with it, but it is just for the app itself but will be just fine in most cases and is probably what you want to do.
-  Edit "settings.json" and change the "youtubedl_path" variable to the one you have installed in a base location. This one allows you the option to run via command line when needed... but that defeats that whole point of the UI so yeah lol.

**Comment by axcore** [comment]
This project is abandoned. You can find a list of forks [here](https://www.reddit.com/r/youtubedl/wiki/info-guis/).
