### ISSUE TITLE
"python setup.py egg_info"

### ISSUE THREAD

**Issue by EEEmill** [MrS0m30n3/youtube-dl-gui#94]
Hello, I´ve got an error while I´m installing your application on my Mac OS X.

"Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-728Jwt/youtube-dlg/"

How to fix it?

Thanks!

**Comment by vincentcox** [comment]
Got the same problem. Upgraded pip and used the sudo -H tag, but with no result.

**Comment by aflores** [comment]
Same here

**Comment by MrS0m30n3** [comment]
I don't think the "egg_info" parameter is available on distutils. Don't have a Mac so i cant say lot about it.

**Comment by maurus56** [comment]
Had that same problem using just youtube_dl in my mac, update pip, update youtube_dl and run pip with sudo (Error code 1 is defined in errno.h and means Operation not permitted):

sudo pip install --upgrade pip
sudo pip install --upgrade youtube-dl

Else the problem could be coming from the conversion to mp3 if you dont have ffmpeg installed.
Hope this solves it for you

**Comment by rcross** [comment]
still have this problem on mac

**Comment by MrS0m30n3** [comment]
Maybe if someone is interested he/she can package youtube-dl-gui for Mac and also provide support.

**Comment by bergerjac** [comment]
hello everyone. I started to make a homebrew Formula, but my system is not setup for a developer as it once was.  I kept running into undocumented obstacle after invisible roadblock.

I used _[homebrew 'create' docs](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#an-introduction)_ combined with _[Python for (Brew) Formula Authors](https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md)_

Note: do _**NOT**_ use `pip install wxPython` because the pip package is wxPython 4 and youtube-dl-gui depends on wxPython 3

I did a `brew create` on the 0.4 [release](https://github.com/MrS0m30n3/youtube-dl-gui/releases), then edited it to this point [file at bottom]. 

I then did a `brew install --interactive youtube-dl-gui`, but like I said... errors.

So, I'm passing the torch to you ;)

- [ ] download the src files
- [ ] use the doc links above to fulfill the 'brew create' process
- [ ] edit the 'test' section in the file below

```ruby
class YoutubeDlGui < Formula
  desc "A cross platform front-end GUI of the popular youtube-dl written in wxPython."
  homepage "https://github.com/MrS0m30n3/youtube-dl-gui"
  url "https://github.com/MrS0m30n3/youtube-dl-gui/archive/0.4.tar.gz"
  version "0.4"
  sha256 "70d7729a51a463f8b4d05e765681cff8f7444282ab5f29a4b71cc2f0fba00065"

  resource "wxPython" do
    url "https://downloads.sourceforge.net/project/wxpython/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2"
    sha256 "d54129e5fbea4fb8091c87b2980760b72c22a386cb3b9dd2eebc928ef5e8df61"
  end

  resource "twodict" do
    url "https://pypi.python.org/packages/49/96/03307c666c1ce0c04bdc23fb69f758b4076eff39d15c56f943ba4b527e21/twodict-1.2.tar.gz#md5=6424b81639e3ed31d67ddd03f81df643"
    sha256 "20dbdfa7f14a285454d34bba1e7714aad15a376ddfd0a1c0a3c24a14763bdb45"
  end

  include Language::Python::Virtualenv  

  def install
    virtualenv_install_with_resources
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test youtube-dl-gui`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end
```

**Comment by MrS0m30n3** [comment]
Hi, @bergerjac

Here it's also the [old homebrew script](https://github.com/pr0d1r2/homebrew/blob/880a5c30a8c5e90990f68fcc0e9d98a0273982f2/Library/Formula/youtube-dl-gui.rb). You might find it useful.

**Comment by LissieTilbrook** [comment]
This happens in Ubuntu 18.04 also! The WebUpd8 PPA is not updated for Bionic... so please remove the "mac" tag because it happens **in Ubuntu** also!

I tried `pip` and `pip2` and got this... **In Ubuntu**

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3LSK66/youtube-dlg/
```

This is **NOT** a Mac-only issue.

**Comment by Areahints** [comment]
Output of Error

`pip install youtube-dlg`


```
Collecting youtube-dlg
  Downloading https://files.pythonhosted.org/packages/55/28/70620c1ffb8ad7ecb81913a053dc454ad7116d3fbdbd8ca23ac0b19ebb40/Youtube-DLG-0.4.tar.gz (153kB)
    100% |████████████████████████████████| 153kB 13kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_ydlc7ml/youtube-dlg/setup.py", line 69, in <module>
        from youtube_dl_gui import (
      File "/tmp/pip-install-_ydlc7ml/youtube-dlg/youtube_dl_gui/__init__.py", line 25
        print error
                  ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_ydlc7ml/youtube-dlg/

```

**Comment by MrS0m30n3** [comment]
@Areahints 

You are using Python3. Try using Python2.

**Comment by mrmeszaros** [comment]
@MrS0m30n3 do you plan to add Python3 support?

**Comment by chriskol** [comment]
I tried using Python2

```
Collecting youtube-dlg
  Using cached https://files.pythonhosted.org/packages/55/28/70620c1ffb8ad7ecb81913a053dc454ad7116d3fbdbd8ca23ac0b19ebb40/Youtube-DLG-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    No module named wx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hr/21b37k_j2kd1vsjsmf_m24g80000gn/T/pip-install-e11Kba/youtube-dlg/
```
